<script setup lang="ts">
// Embed the existing capability tree SVG generated by scripts/render_feature_tree.py.
// Reuse the single source instead of redrawing it; adapt it to dark mode with a CSS filter.
</script>

<template>
  <div class="cap-tree">
    <img
      class="cap-tree__img"
      src="/assets/har-skills-feature-tree.svg"
      alt="HAR Skills capability tree — six domains: Agent Access, Ingest & Parse, Inspect & Search, Analyze, Operate, Compare & Export"
      loading="lazy"
    />
  </div>
</template>

<style scoped>
.cap-tree {
  width: 100%;
  border: 1px solid var(--har-line);
  border-radius: 10px;
  padding: 1rem;
  background: var(--vp-bg, #fff);
  overflow: hidden;
}
.dark .cap-tree {
  background: #0f172a;
}
.cap-tree__img {
  display: block;
  width: 100%;
  height: auto;
}
.dark .cap-tree__img {
  /* The SVG uses a light color scheme; invert it and slightly raise brightness in dark mode. */
  filter: invert(0.92) hue-rotate(180deg) brightness(0.95);
}
</style>
